---
- name: Get OS version from RHEL servers
  hosts: rhel_servers
  gather_facts: yes

  pre_tasks:
    - name: Create CSV file with header
      local_action: copy content="Hostname,OS,Version\n" dest="./os_versions.csv" mode=0644
      run_once: true
      delegate_to: localhost

  tasks:
    - name: Set OS version fact
      set_fact:
        os_info: "{{ ansible_distribution }},{{ ansible_distribution_version }}"

    - name: Append OS version to CSV on control node
      local_action: shell echo "{{ inventory_hostname }},{{ os_info }}" >> ./os_versions.csv
      delegate_to: localhost
      become: false
