---
- name: Uncompress tgz and change ownership
  hosts: server1,server2
  become: yes
  tasks:
    - name: Ensure target directory exists
      file:
        path: /opt/splnkforwarder
        state: directory
        owner: splnkmon
        group: splnkmon
        mode: '0755'

    - name: Uncompress abc.tgz using command
      command: tar -xzf /tmp/abc.tgz -C /opt/splnkforwarder

    - name: Set ownership for extracted files
      file:
        path: /opt/splnkforwarder
        state: directory
        recurse: yes
        owner: splnkmon
        group: splnkmon
